/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutfitRouteImport } from './routes/outfit'
import { Route as PrepareRouteImport } from './routes/prepare'
import { Route as ResultRouteImport } from './routes/result'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SessionRouteImport } from './routes/session'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SkinRouteImport } from './routes/skin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitRoute = OutfitRouteImport.update({
  id: '/outfit',
  path: '/outfit',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareRoute = PrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinRoute = SkinRouteImport.update({
  id: '/skin',
  path: '/skin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/outfit': typeof OutfitRoute
  '/prepare': typeof PrepareRoute
  '/result': typeof ResultRoute
  '/routine': typeof RoutineRoute
  '/rules': typeof RulesRoute
  '/session': typeof SessionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skin': typeof SkinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/outfit': typeof OutfitRoute
  '/prepare': typeof PrepareRoute
  '/result': typeof ResultRoute
  '/routine': typeof RoutineRoute
  '/rules': typeof RulesRoute
  '/session': typeof SessionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skin': typeof SkinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/outfit': typeof OutfitRoute
  '/prepare': typeof PrepareRoute
  '/result': typeof ResultRoute
  '/routine': typeof RoutineRoute
  '/rules': typeof RulesRoute
  '/session': typeof SessionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skin': typeof SkinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/outfit'
    | '/prepare'
    | '/result'
    | '/routine'
    | '/rules'
    | '/session'
    | '/sitemap.xml'
    | '/skin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/outfit'
    | '/prepare'
    | '/result'
    | '/routine'
    | '/rules'
    | '/session'
    | '/sitemap.xml'
    | '/skin'
  id:
    | '__root__'
    | '/'
    | '/outfit'
    | '/prepare'
    | '/result'
    | '/routine'
    | '/rules'
    | '/session'
    | '/sitemap.xml'
    | '/skin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OutfitRoute: typeof OutfitRoute
  PrepareRoute: typeof PrepareRoute
  ResultRoute: typeof ResultRoute
  RoutineRoute: typeof RoutineRoute
  RulesRoute: typeof RulesRoute
  SessionRoute: typeof SessionRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkinRoute: typeof SkinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfit': {
      id: '/outfit'
      path: '/outfit'
      fullPath: '/outfit'
      preLoaderRoute: typeof OutfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare': {
      id: '/prepare'
      path: '/prepare'
      fullPath: '/prepare'
      preLoaderRoute: typeof PrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skin': {
      id: '/skin'
      path: '/skin'
      fullPath: '/skin'
      preLoaderRoute: typeof SkinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OutfitRoute: OutfitRoute,
  PrepareRoute: PrepareRoute,
  ResultRoute: ResultRoute,
  RoutineRoute: RoutineRoute,
  RulesRoute: RulesRoute,
  SessionRoute: SessionRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkinRoute: SkinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
