/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkinRouteImport } from './routes/skin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SessionRouteImport } from './routes/session'
import { Route as PrepareRouteImport } from './routes/prepare'
import { Route as IndexRouteImport } from './routes/index'

const SkinRoute = SkinRouteImport.update({
  id: '/skin',
  path: '/skin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareRoute = PrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prepare': typeof PrepareRoute
  '/session': typeof SessionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skin': typeof SkinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prepare': typeof PrepareRoute
  '/session': typeof SessionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skin': typeof SkinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prepare': typeof PrepareRoute
  '/session': typeof SessionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skin': typeof SkinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prepare' | '/session' | '/sitemap.xml' | '/skin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prepare' | '/session' | '/sitemap.xml' | '/skin'
  id: '__root__' | '/' | '/prepare' | '/session' | '/sitemap.xml' | '/skin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrepareRoute: typeof PrepareRoute
  SessionRoute: typeof SessionRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkinRoute: typeof SkinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skin': {
      id: '/skin'
      path: '/skin'
      fullPath: '/skin'
      preLoaderRoute: typeof SkinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare': {
      id: '/prepare'
      path: '/prepare'
      fullPath: '/prepare'
      preLoaderRoute: typeof PrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrepareRoute: PrepareRoute,
  SessionRoute: SessionRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkinRoute: SkinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
